server:
  port: 8888

spring:
  application:
    name: eqa-config-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: http://143.244.132.119/root/eqa-config-server.git
          username: root
          password: technojade
          clone-on-start: true
          timeout: 30 # in sec
          refreshRate: 3600 #in sec

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'