server:
  port: 8761

eureka:
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30


spring:
  security:
    user:
      name: admin
      password: admin
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'