server:
  port: 8766
  error:
    include-message=always: always
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

spring:
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true
  application:
    name: eqa-gateway-service
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  client:
    service-url:
      default-zone=http://localhost:8761/eureka/:
  cloud:
    gateway:
      routes:
        - id: microservice-one
          uri: lb://microservice-one
          Predicates:
            - Path=/ms-one/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: customCircuitBreaker
                fallbackUri: forward:/custom-fallback

        - id: microservice-two
          uri: lb://microservice-two
          Predicates:
            - Path=/ms-two/**
resilience4j:
  circuitbreaker:
    instances:
      customCircuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
  timelimiter:
    instances:
      customCircuitBreaker:
        timeoutDuration: 3s


#validateTokenUrl: https://eqa.datadimens.com:8994/IDENTITY-SERVICE/validatetoken

