spring:
  config:
    import: optional:configserver:http://admin:admin@localhost:8888
  application:
      name: gateway
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN


#  ssl:
#    bundle:
#      pem:
#        eqa:
#          truststore:
#            certificate: "classpath:eqa_cert.crt"


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

#logging:
#  level:
#    org.springframework.web.HttpLogging: TRACE
#    reactor.netty.http.server: DEBUG
#    reactor.netty.http.client: DEBUG

