server:
  port: 8089
spring:
  application:
    name: microservice-two
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  file:
    name: /home/logs/${spring.application.name}