spring:
  application:
    name: microservice-one
server:
    port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'