server:
  port: 8765
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
  management:
    endpoints:
      web:
        exposure:
          include: health, info
      enabled-by-default: true
      base-path: /admin
  client:
    service-url:
      default-zone=http://localhost:8761/eureka/:
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: lb://Microservice1
          Predicates:
            - Path=/serviceA/**
          filters:
            - FallbackFilter=_
        - id: Microservice2
          uri: lb://Microservice2
          Predicates:
            - Path=/serviceB/**
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
  timelimiter:
    instances:
      default:
        timeDuration: 3s



